version: '3.9'

services:
  java_app:
    container_name: java_app
    image: docker_demo_image
    build: .
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/docker_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      
    depends_on:
      - java_db
        
  java_db:
    container_name: java_db
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER= postgres 
      - POSTGRES_PASSWORD= postgres 
      - POSTGRES_DB=docker_db
    volumes:
      - pgdata:/var/lib/posgtresql/data
      
volumes:
  pgdata: {}
    
    